[RGBDevice]
Count=40
DeviceHWID1=USB\VID_04F2&PID_0117
DeviceHWID2=USB\VID_04F2&PID_011A
DeviceHWID3=USB\VID_04F2&PID_0119
DeviceHWID4=EC\ACPI1
DeviceHWID5=EC\ACPI2
; Sunrex Keyboard
DeviceHWID6=USB\VID_05AF&PID_766D
DeviceHWID7=USB\VID_05AF&PID_766A
DeviceHWID8=USB\VID_05AF&PID_766B
DeviceHWID9=USB\VID_05AF&PID_766C
DeviceHWID10=USB\VID_05AF&PID_766E
; Sunrex Keyboard 2024
DeviceHWID11=USB\VID_05AF&PID_666A
DeviceHWID12=USB\VID_05AF&PID_666B
DeviceHWID13=USB\VID_05AF&PID_666C
DeviceHWID14=USB\VID_05AF&PID_666D
DeviceHWID15=USB\VID_05AF&PID_666E
DeviceHWID16=USB\VID_05AF&PID_866A
DeviceHWID17=USB\VID_05AF&PID_866B
DeviceHWID18=USB\VID_05AF&PID_866C
DeviceHWID19=USB\VID_05AF&PID_866D
DeviceHWID20=USB\VID_05AF&PID_866E
; Sunrex Keyboard 2025
DeviceHWID21=USB\VID_05AF&PID_667A
DeviceHWID22=USB\VID_05AF&PID_667B
DeviceHWID23=USB\VID_05AF&PID_667C
DeviceHWID24=USB\VID_05AF&PID_667D
DeviceHWID25=USB\VID_05AF&PID_667E
DeviceHWID26=USB\VID_05AF&PID_867A
DeviceHWID27=USB\VID_05AF&PID_867B
DeviceHWID28=USB\VID_05AF&PID_867C
DeviceHWID29=USB\VID_05AF&PID_867D
DeviceHWID30=USB\VID_05AF&PID_867E
DeviceHWID31=USB\VID_05AF&PID_767A
DeviceHWID32=USB\VID_05AF&PID_767B
DeviceHWID33=USB\VID_05AF&PID_767C
DeviceHWID34=USB\VID_05AF&PID_767D
DeviceHWID35=USB\VID_05AF&PID_767E
; Darfon device 
DeviceHWID36=USB\VID_0D62&PID_BA51
; Darfon device 2025
DeviceHWID37=USB\VID_0D62&PID_A00A
DeviceHWID38=USB\VID_0D62&PID_A01A
DeviceHWID39=USB\VID_0D62&PID_A20A
DeviceHWID40=USB\VID_0D62&PID_A21A

[EC\ACPI1]
DeviceName=AcerECKeyboardController
[EC\ACPI2]
DeviceName=AcerECLightbarController
[USB\VID_04F2&PID_0117]
DeviceName=AcerUSBController
UsagePage=FF02
[USB\VID_04F2&PID_011A]
DeviceName=AcerUSBController
UsagePage=FF02
[USB\VID_04F2&PID_0119]
DeviceName=AcerUSBController
UsagePage=FF02
[USB\VID_05AF&PID_766D]
DeviceName=SunrexUSBKeyboard
UsagePage=FF02
[USB\VID_05AF&PID_766A]
DeviceName=SunrexUSBKeyboard
UsagePage=FF02
[USB\VID_05AF&PID_766B]
DeviceName=SunrexUSBKeyboard
UsagePage=FF02
[USB\VID_05AF&PID_766C]
DeviceName=SunrexUSBKeyboard
UsagePage=FF02
[USB\VID_05AF&PID_766E]
DeviceName=SunrexUSBKeyboard
UsagePage=FF02
[USB\VID_05AF&PID_666A]
DeviceName=SunrexUSBKeyboard
UsagePage=FF02
[USB\VID_05AF&PID_666B]
DeviceName=SunrexUSBKeyboard
UsagePage=FF02
[USB\VID_05AF&PID_666C]
DeviceName=SunrexUSBKeyboard
UsagePage=FF02
[USB\VID_05AF&PID_666D]
DeviceName=SunrexUSBKeyboard
UsagePage=FF02
[USB\VID_05AF&PID_666E]
DeviceName=SunrexUSBKeyboard
UsagePage=FF02
[USB\VID_05AF&PID_866A]
DeviceName=SunrexUSBKeyboard
UsagePage=FF02
[USB\VID_05AF&PID_866B]
DeviceName=SunrexUSBKeyboard
UsagePage=FF02
[USB\VID_05AF&PID_866C]
DeviceName=SunrexUSBKeyboard
UsagePage=FF02
[USB\VID_05AF&PID_866D]
DeviceName=SunrexUSBKeyboard
UsagePage=FF02
[USB\VID_05AF&PID_866E]
DeviceName=SunrexUSBKeyboard
UsagePage=FF02
[USB\VID_05AF&PID_667A]
DeviceName=SunrexUSBKeyboard
UsagePage=FF02
[USB\VID_05AF&PID_667B]
DeviceName=SunrexUSBKeyboard
UsagePage=FF02
[USB\VID_05AF&PID_667C]
DeviceName=SunrexUSBKeyboard
UsagePage=FF02
[USB\VID_05AF&PID_667D]
DeviceName=SunrexUSBKeyboard
UsagePage=FF02
[USB\VID_05AF&PID_667E]
DeviceName=SunrexUSBKeyboard
UsagePage=FF02
[USB\VID_05AF&PID_867A]
DeviceName=SunrexUSBKeyboard
UsagePage=FF02
[USB\VID_05AF&PID_867B]
DeviceName=SunrexUSBKeyboard
UsagePage=FF02
[USB\VID_05AF&PID_867C]
DeviceName=SunrexUSBKeyboard
UsagePage=FF02
[USB\VID_05AF&PID_867D]
DeviceName=SunrexUSBKeyboard
UsagePage=FF02
[USB\VID_05AF&PID_867E]
DeviceName=SunrexUSBKeyboard
UsagePage=FF02
[USB\VID_05AF&PID_767A]
DeviceName=SunrexUSBKeyboard
UsagePage=FF02
[USB\VID_05AF&PID_767B]
DeviceName=SunrexUSBKeyboard
UsagePage=FF02
[USB\VID_05AF&PID_767C]
DeviceName=SunrexUSBKeyboard
UsagePage=FF02
[USB\VID_05AF&PID_767D]
DeviceName=SunrexUSBKeyboard
UsagePage=FF02
[USB\VID_05AF&PID_767E]
DeviceName=SunrexUSBKeyboard
UsagePage=FF02
[USB\VID_0D62&PID_BA51]
DeviceName=DarfonUSBController
UsagePage=FF01
[USB\VID_0D62&PID_A00A]
DeviceName=DarfonUSBController
UsagePage=FF01
[USB\VID_0D62&PID_A01A]
DeviceName=DarfonUSBController
UsagePage=FF01
[USB\VID_0D62&PID_A20A]
DeviceName=DarfonUSBController
UsagePage=FF01
[USB\VID_0D62&PID_A21A]
DeviceName=DarfonUSBController
UsagePage=FF01


